import type { Metadata } from 'next';
import { LegalArticle, LegalSection } from '@/components/legal/LegalArticle';
import { SITE_NAME, CONTACT_EMAIL } from '@/lib/site';

export const metadata: Metadata = {
  title: 'Disclaimer',
  description:
    'Cipher is an educational research tool, not investment advice. Read the full financial disclaimer before relying on any output.',
  alternates: { canonical: '/disclaimer' },
};

const toc = [
  { id: 'not-advice', label: 'Not investment advice' },
  { id: 'no-relationship', label: 'No advisory relationship' },
  { id: 'ai-generated', label: 'AI-generated content' },
  { id: 'data', label: 'Third-party data' },
  { id: 'backtests', label: 'Backtests & past performance' },
  { id: 'risk', label: 'Your own risk' },
  { id: 'contact', label: 'Contact' },
];

export default function DisclaimerPage() {
  return (
    <LegalArticle
      eyebrow="Legal"
      title="Disclaimer"
      summary={`${SITE_NAME} produces educational, source-cited research. It is a software tool — not a financial adviser, broker, or analyst — and nothing it outputs is a recommendation to buy, hold, or sell any security.`}
      toc={toc}
    >
      <LegalSection id="not-advice" heading="1. Not investment advice">
        <p>
          All content produced by {SITE_NAME} — including sentiment scores, bull and bear
          drivers, forward outlooks, price-target context, confidence levels, and any
          Buy / Hold / Sell language — is provided for <strong>informational and
          educational purposes only</strong>. It does not constitute, and must not be
          relied upon as, investment, financial, legal, tax, or accounting advice, nor a
          recommendation, offer, or solicitation to buy, hold, or sell any security or to
          adopt any investment strategy.
        </p>
        <p>
          {SITE_NAME} does not consider your personal financial situation, objectives, risk
          tolerance, or needs. Any decision you make is yours alone.
        </p>
      </LegalSection>

      <LegalSection id="no-relationship" heading="2. No advisory or fiduciary relationship">
        <p>
          {SITE_NAME} is not a registered investment adviser, broker-dealer, or financial
          planner, and is not registered with or endorsed by the U.S. Securities and
          Exchange Commission, FINRA, or any other regulatory body. Using {SITE_NAME} does
          not create an advisory, brokerage, fiduciary, or other professional relationship
          between you and the operator of {SITE_NAME}. Consult a licensed financial
          professional before making any investment decision.
        </p>
      </LegalSection>

      <LegalSection id="ai-generated" heading="3. AI-generated content may be wrong">
        <p>
          {SITE_NAME}&rsquo;s reports are generated by large language models and automated
          data pipelines. Although the system is designed to ground every claim in a
          retrieved source, AI systems can still misread data, draw faulty inferences,
          surface outdated information, or produce content that is incomplete or simply
          incorrect. Source citations indicate where information was drawn from; they are
          not a guarantee of accuracy. <strong>Always verify any figure or claim against
          the primary source before acting on it.</strong>
        </p>
      </LegalSection>

      <LegalSection id="data" heading="4. Third-party data is provided &ldquo;as is&rdquo;">
        <p>
          Market data, fundamentals, filings, analyst commentary, and social or community
          sentiment are obtained from third-party providers. {SITE_NAME} does not warrant
          the accuracy, completeness, timeliness, or availability of this data. Prices and
          other figures may be delayed, estimated, adjusted, or in error, and should not be
          treated as real-time or definitive.
        </p>
      </LegalSection>

      <LegalSection id="backtests" heading="5. Backtests and past performance">
        <p>
          {SITE_NAME} reports historical calibration metrics — hit rates, alpha-versus-sector
          estimates, Brier scores, and reliability diagrams — to be transparent about how its
          engine has performed. These are research artifacts. <strong>Past performance and
          backtested results are hypothetical, are not indicative of future results, and do
          not represent actual trading.</strong> Backtests are subject to limitations
          including, without limitation, survivorship bias, look-ahead bias, and overfitting.
        </p>
      </LegalSection>

      <LegalSection id="risk" heading="6. You assume all risk">
        <p>
          Investing in securities involves substantial risk, including the possible loss of
          principal. You are solely responsible for your own investment decisions and for
          conducting your own due diligence. To the fullest extent permitted by law, the
          operator of {SITE_NAME} disclaims all liability for any loss or damage arising from
          your use of, or reliance on, the service or its output.
        </p>
      </LegalSection>

      <LegalSection id="contact" heading="7. Contact">
        <p>
          Questions about this disclaimer can be sent to{' '}
          <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
        </p>
      </LegalSection>
    </LegalArticle>
  );
}
